spring:
  application:
    name: pnm-produttori
    profiles:
      active: dev
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/pnm-produttori
    username: postgres
    password: pass
    driverClassName: org.postgresql.Driver